version: 0.2
            
phases:
  install:
    commands:
      - gem install jekyll bundler
  build:
    commands:
      - bundle exec jekyll build
  artifacts:
    secondary-artifacts:
      site:
        - _site/**/*
      posts:
        files:
          - _posts/**/*

