version: 0.2
            
phases:
  install:
    commands:
      - gem install jekyll bundler
      - bundle install --path vendor/cache
  build:
    commands:
      - bundle exec jekyll build
artifacts:
  secondary-artifacts:
    site:
      files:
        - _site/**/*
    posts:
      files:
        - _posts/**/*

