version: 0.2
            
phases:
  install:
    commands:
      - gem install jekyll bundler
      - bundle install --path vendor/cache
  build:
    commands:
      - bundle exec jekyll build
artifacts:
  files:
    - _site/**/*
  name: site-$(date +%Y-%m-%d) 
  secondary-artifacts:
    posts:
      files:
        - _posts/**/*

